API_ID: 5677964080:AAFSGPzh2H7IC5j3NqWhWxPZdYZzjhQHkhQ
API_HASH: b35415778f7bf2cc6b0269d6c153c6a6
BOT_TOKEN: 5677964080:AAFSGPzh2H7IC5j3NqWhWxPZdYZzjhQHkhQ


MONGO_URL: mongodb+srv://sadewa:0504015145@cluster0.lvpatpo.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13043.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:13043
REDIS_PORT: 13043
REDIS_PASS: AwCG8Ov0CaYvJv7e5OwIoG43iOMBqbUT

SESSION_API_ID: 5677964080:AAFSGPzh2H7IC5j3NqWhWxPZdYZzjhQHkhQ
SESSION_API_HASH: b35415778f7bf2cc6b0269d6c153c6a6
SESSION_STRING: BQAhIHQApQwKL5Mf6LBw2aXNjenvcsqxC22LQmdaIcvUjZrYN2p0vKhWigDSpHTRKd8XJVkg6I0w0MAgAsfTE9RG6TlJgly_OqTBRlVp5L203kQqgQJvy9i8-Xl_hxLJkjekS-apxB9xZ5lQt9T04Jm0ZjZo78JQIgdQFD2YAElXmSlNP5HheRaiU4Y5eSTOPWOTnOzcdGY5_DbRwEb2OlAoZpnpYUGqoQl6JWkKq-af230M-DScEJSCtQio7M0r_ZJ6mwDX_1efsBw2hASFU3k0ydPO8dkWFwG8YIU2zjGA2Iv3_JXLgg8V58aWEZstAeyQzMxzHdu8IoaO4Q73s-Wwxc1HWAAAAABNx0wIAA

ADMINS: 
  - 1304906760

OWNER: 1304906760

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

